### ISSUE TITLE
Forks should probably be ordered in reverse chronological order.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/cerulean#20]
When you reply to a message in Twitter or HN etc you expect to see your reply immediately under the thing you replied to... even if it's a fork.  So, perversely, this means that forks should be ordered **reverse** chronologically, but replies should be ordered **forward** chronologically.

This means that if these msgs are posted in sequence A,B,C,D (in horizontal layout), rather than this:

```
A
  B
    C
  D
```

They should be ordered as:

```
A
  D
  B
     C
```

This is high priority to fix, as the current (mis)behaviour is quite jarring.

**Comment by kegsay** [comment]
So for the scenario: (horizontal layout)
```
A
  B
  C
    D
      F
        G
    E
  H 
```

we'd expect it to be presented as:
```
A
  H
  C
    E
    D
      F
        G
  B
```
which in vertical view maps to:
```
A
|__H
|__C
|   |__E
|   |__D
|      F
|      G
|__B

```


Isn't this just entirely reverse chronological full stop?

**Comment by kegsay** [comment]
As I understand it, yes it should be reverse chronological full stop. The only time we care about sort ordering is for forks (technically siblings), as direct replies (no matter how early/late they happen) get forced beneath and indented.

**Comment by kegsay** [comment]
This was done.
