### ISSUE TITLE
Send m.tag to mark rooms as low priority after join

### ISSUE THREAD

**Issue by neilalexander** [matrix-org/cerulean#22]
Currently Cerulean joins lots of rooms, so it would be nice if we could send an `m.tag` account data after joining each room with `{"tags":{"m.lowpriority":{}}}` so that Element Web lists them separately as low-priority rooms, rather than filling up the main room list.

**Comment by Half-Shot** [comment]
Alternatively, use https://github.com/matrix-org/matrix-doc/pull/1840 and petition element to hide these rooms by default. Profile rooms should be hidden anyway.

**Comment by neilalexander** [comment]
Typed rooms would definitely be the right answer, but in the meantime, we sadly don't have them. :-(

**Comment by kegsay** [comment]
https://github.com/matrix-org/cerulean/commit/aff3707374ee829f9e4331592197395b3a0af56e
