### ISSUE TITLE
GitHub Discussions API

### ISSUE THREAD

**Issue by erlend-sh** [matrix-org/cerulean#46]
This API is finally becoming available:
https://github.com/github/feedback/discussions/43#discussioncomment-339955

Being able to mirror and import from this API is very important, seeing as GH Discussions is not an open source platform and [does not yet support exports](https://github.com/github/feedback/discussions/3315).

This could potentially allow the Matrix team to use Cerulean in a real world setting with real utility:
- Enable GH Discussions on certain central Matrix/Element repos
- Mirror those discussions with Cerulean

**Comment by Half-Shot** [comment]
I'm not sure this is the right repo for this request, cerulean is just a matrix client. https://github.com/Half-Shot/matrix-github/pull/47 is  a PR where I am working on supporting bridging Matrix<->GH Discussions. Cerulean support may follow.
